name: Update Theme

on:
  workflow_dispatch:

jobs:
  update-theme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          submodules: true
          fetch-depth: 0

      - name: Update theme
        run: git submodule update --remote --checkout

      - name: Commit theme update
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "CI: Update theme"
          branch: main

      - name: Deploy
        if: steps.commit.outputs.changes_detected == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh workflow run hugo.yaml --ref main